export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_FAILED = 'LOAD_PROPERTIES_FAILED';
export const LOAD_SAVED_PROPERTIES_SUCCESS = 'LOAD_SAVED_PROPERTIES_SUCCESS';
export const LOAD_SAVED_PROPERTIES_FAILED = 'LOAD_SAVED_PROPERTIES_FAILED';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAIL = 'ADD_PROPERTY_FAIL';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAIL = 'DELETE_PROPERTY_FAIL';